'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ExternalLink, LocateFixed, Minus, Plus, RotateCcw } from 'lucide-react';

type Level='home'|'projects'|'jobpilot'|'ironakhada'|'portfolio'|'photography'|'pylauncher'|'experience'|'skills'|'philosophy'|'contact'|'about';
type Point={x:number;y:number};
type Node={id:string;label:string;displayLabel?:string;x:number;y:number;size?:number;description?:string;depth?:number;homeRole?:'primary'|'satellite'};
type Graph={center:Node;nodes:Node[]};
type Detail={eyebrow:string;title:string;body:string;tags:string[];links?:{label:string;href:string}[]};
const n=(id:string,label:string,description?:string,extra?:Partial<Node>):Node=>({id,label,x:0,y:0,description,...extra});

const homeGraph:Graph={center:{id:'nayan',label:'NAYAN ASATI',x:0,y:0,size:180},nodes:[
 n('projects','PROJECTS',undefined,{homeRole:'primary',size:88}),n('experience','EXPERIENCE',undefined,{homeRole:'primary',size:88}),n('skills','SKILLS',undefined,{homeRole:'primary',size:88}),n('philosophy','PHILOSOPHY',undefined,{homeRole:'primary',size:88}),n('contact','CONTACT',undefined,{homeRole:'primary',size:88}),n('about','ABOUT',undefined,{homeRole:'primary',size:88}),
 n('jobpilot','JOBPILOT AI','AI-assisted job outreach workflow',{displayLabel:'JOBPILOT',homeRole:'satellite',size:58}),n('ironakhada','IRON AKHADA','Fitness-focused web project',{displayLabel:'IRON AKHADA',homeRole:'satellite',size:58}),n('portfolio','NAYAN ASATI PORTFOLIO','Interactive Flow portfolio',{displayLabel:'PORTFOLIO',homeRole:'satellite',size:58}),n('photography','GHOUL PHOTOGRAPHY','Cinematic photography archive',{displayLabel:'PHOTOGRAPHY',homeRole:'satellite',size:58}),n('pylauncher','PYLAUNCHER','Python utility project',{displayLabel:'PYLAUNCHER',homeRole:'satellite',size:58}),
 n('engineering','ENGINEER','Analyser Instrument Company · Nov 2025 – Jun 2026',{displayLabel:'ANALYSER',homeRole:'satellite',size:58}),n('manufacturing','ASHOK LEYLAND','Graduate Apprentice Trainee · Aug 2024 – Jul 2025',{displayLabel:'ASHOK LEYLAND',homeRole:'satellite',size:58}),n('proposal','ROOT-CAUSE','Engineering problem solving and quality improvement',{displayLabel:'ROOT-CAUSE',homeRole:'satellite',size:58})
]};

const graphs:Record<Exclude<Level,'home'>,Graph>={
 projects:{center:{id:'projects',label:'PROJECTS',x:0,y:0,size:138},nodes:[n('jobpilot','JOBPILOT AI','AI-assisted job outreach workflow'),n('ironakhada','IRON AKHADA','Fitness radio experience'),n('portfolio','NAYAN ASATI PORTFOLIO','Interactive portfolio'),n('photography','GHOUL PHOTOGRAPHY','Cinematic archive'),n('pylauncher','PYLAUNCHER','Python utility project')]},
 jobpilot:{center:{id:'jobpilot',label:'JOBPILOT AI',x:0,y:0,size:148},nodes:[n('jp-problem','PROBLEM','Reduce repetitive job-search and outreach work.'),n('jp-system','SYSTEM','Import, matching, drafting, approval and outreach.'),n('jp-tech','TECHNOLOGY','Modern web stack with AI-assisted workflows.'),n('jp-next','NEXT.JS','Application framework.'),n('jp-typescript','TYPESCRIPT','Typed application foundation.'),n('jp-ai','AI AGENT','Automation layer.'),n('jp-api','APIS','Connect workflow stages and services.') ]},
 ironakhada:{center:{id:'ironakhada',label:'IRON AKHADA',x:0,y:0,size:142},nodes:[n('ia-fitness','FITNESS','The product direction and training focus.'),n('ia-journey','USER JOURNEY','Entering, listening, discovering and training.'),n('ia-build','BUILD','Responsive product implementation.'),n('ia-audio','STREAMED AUDIO','Core listening function.'),n('ia-presence','LIVE PRESENCE','Listener presence in the experience.'),n('ia-stations','TRAINING STATIONS','Training-focused navigation.') ]},
 portfolio:{center:{id:'portfolio',label:'NAYAN ASATI PORTFOLIO',x:0,y:0,size:148},nodes:[n('pf-flow','FLOW','Portfolio navigation as a connected system.'),n('pf-interactive','INTERACTIVE','Drag, zoom, hover and click.'),n('pf-phases','PHASES','Foundation through polish.'),n('pf-responsive','RESPONSIVE','Desktop and mobile experience.'),n('pf-trace','TRACE','Path-aware navigation.'),n('pf-access','ACCESSIBILITY','Keyboard and focus interaction.') ]},
 photography:{center:{id:'photography',label:'GHOUL PHOTOGRAPHY',x:0,y:0,size:144},nodes:[n('gp-archive','ARCHIVE','Cinematic photography archive.'),n('gp-gallery','GALLERY','Responsive visual browsing.'),n('gp-automation','AUTOMATION','Gemini AI and Instagram API workflows.'),n('gp-responsive','RESPONSIVE','Visual experience across screen sizes.'),n('gp-content','CONTENT','Repeatable content workflow.') ]},
 pylauncher:{center:{id:'pylauncher',label:'PYLAUNCHER',x:0,y:0,size:142},nodes:[n('pl-python','PYTHON','Python application development.'),n('pl-launcher','LAUNCHER','Utility-oriented launcher experience.'),n('pl-interface','INTERFACE','Desktop interaction and usability.'),n('pl-utility','UTILITY','Practical desktop workflow.') ]},
 experience:{center:{id:'experience',label:'EXPERIENCE',x:0,y:0,size:138},nodes:[n('ex-engineering','ENGINEER','Analyser Instrument Company · Nov 2025 – Jun 2026'),n('ex-manufacturing','ASHOK LEYLAND','Graduate Apprentice Trainee · Aug 2024 – Jul 2025'),n('ex-proposals','TECHNICAL PROPOSALS','Compliance documentation and tender proposals.'),n('ex-support','CUSTOMER SUPPORT','Product specifications and technical queries.'),n('ex-operations','SHIFT OPERATIONS','100+ person team, SAP NetWeaver and Siemens HMI.'),n('ex-quality','QUALITY','Root-cause analysis and enhanced inspection measures.') ]},
 skills:{center:{id:'skills',label:'SKILLS',x:0,y:0,size:138},nodes:[n('sk-javascript','JAVASCRIPT','Core web language.'),n('sk-react','REACT','Interactive UI development.'),n('sk-htmlcss','HTML / CSS','Web structure and styling.'),n('sk-python','PYTHON','Application development.'),n('sk-fastapi','FASTAPI','Python API development.'),n('sk-node','NODE.JS','JavaScript runtime and web tooling.'),n('sk-rest','REST APIS','API-driven integrations.'),n('sk-git','GIT / GITHUB','Source control and delivery.'),n('sk-actions','GITHUB ACTIONS','Repository automation and CI.'),n('sk-responsive','RESPONSIVE WEB','Mobile and desktop interfaces.'),n('sk-bootstrap','BOOTSTRAP','Web UI toolkit.'),n('sk-deploy','NETLIFY / RENDER','Deployment experience.'),n('sk-formspree','FORMSPREE','Form handling and integrations.'),n('sk-search','SEARCH CONSOLE','Google Search Console experience.') ]},
 philosophy:{center:{id:'philosophy',label:'PHILOSOPHY',x:0,y:0,size:144},nodes:[n('ph-root','FIND THE ROOT','Understand the underlying problem first.'),n('ph-system','BUILD THE SYSTEM','Think frontend, backend, deployment and workflow together.'),n('ph-leverage','SHIP WITH LEVERAGE','Use AI-assisted development to move faster.'),n('ph-working','WORKING SOFTWARE','Prefer useful, functioning software over theoretical perfection.'),n('ph-document','DOCUMENT','Make technical decisions and processes understandable.'),n('ph-improve','KEEP IMPROVING','Use feedback, testing and iteration to strengthen the system.') ]},
 contact:{center:{id:'contact',label:'CONTACT',x:0,y:0,size:138},nodes:[n('ct-email','EMAIL','nayanasati2001@gmail.com'),n('ct-linkedin','LINKEDIN','Professional profile and network.'),n('ct-github','GITHUB','Code, experiments and repositories.'),n('ct-phone','PHONE','+91 6262055238'),n('ct-location','LOCATION','Sagar, Madhya Pradesh, India'),n('ct-open','OPEN TO','Professional conversations and opportunities.') ]},
 about:{center:{id:'about',label:'ABOUT',x:0,y:0,size:138},nodes:[n('ab-engineer','ENGINEER','Electrical engineering foundation.'),n('ab-developer','DEVELOPER','Self-taught full-product developer.'),n('ab-education','EDUCATION','B.Tech Electrical Engineering, Gurukul Kangri Vishwavidyalaya.'),n('ab-certifications','CERTIFICATIONS','CSS/Bootstrap/JavaScript/PHP course, AI Tools Workshop and Ashok Leyland apprenticeship.'),n('ab-languages','LANGUAGES','Hindi native and English professional.'),n('ab-location','BASED IN','Sagar, MP, India.'),n('ab-approach','APPROACH','Engineering discipline combined with practical software delivery.') ]}
};

const parentOf:Partial<Record<Level,Level>>={projects:'home',jobpilot:'projects',ironakhada:'projects',portfolio:'projects',photography:'projects',pylauncher:'projects',experience:'home',skills:'home',philosophy:'home',contact:'home',about:'home'};
const childLinks:Record<string,Level|undefined>={projects:'projects',jobpilot:'jobpilot',ironakhada:'ironakhada',portfolio:'portfolio',photography:'photography',pylauncher:'pylauncher',experience:'experience',skills:'skills',philosophy:'philosophy',contact:'contact',about:'about'};
const labels:Record<Level,string>={home:'HOME',projects:'PROJECTS',jobpilot:'JOBPILOT AI',ironakhada:'IRON AKHADA',portfolio:'PORTFOLIO',photography:'GHOUL PHOTOGRAPHY',pylauncher:'PYLAUNCHER',experience:'EXPERIENCE',skills:'SKILLS',philosophy:'PHILOSOPHY',contact:'CONTACT',about:'ABOUT'};
const graphFor=(level:Level):Graph=>level==='home'?homeGraph:graphs[level];
const nodeFor=(level:Level)=>graphFor(level).center;

const details:Record<Level,Detail>={
 home:{eyebrow:'NAYAN / HOME',title:'Engineer → Developer',body:'Self-taught developer who builds full products end-to-end across frontend, backend and deployment. The engineering background adds a habit of root-cause analysis, process documentation and cross-functional problem solving.',tags:['Web Development','Engineering','AI-assisted development','End-to-end delivery']},
 projects:{eyebrow:'NAYAN / PROJECTS',title:'Selected work',body:'Projects are treated as systems: understand the problem, choose the stack, build the experience and make the result usable. The network now separates each project and its supporting capabilities.',tags:['JobPilot AI','Iron Akhada','Portfolio','Ghoul Photography','PyLauncher']},
 jobpilot:{eyebrow:'PROJECT / JOBPILOT AI',title:'Job outreach as a system',body:'An AI-assisted job outreach workflow designed around repeatable stages instead of disconnected manual work.',tags:['Next.js','TypeScript','AI','APIs'],links:[{label:'OPEN GITHUB',href:'https://github.com/Nayan1209/jobpilot-ai'}]},
 ironakhada:{eyebrow:'PROJECT / IRON AKHADA',title:'Fitness radio experience',body:'A web-based fitness radio experience with streamed audio, live listener presence, training stations and immersive UI.',tags:['Next.js','React','TypeScript','Cloudflare']},
 portfolio:{eyebrow:'PROJECT / FLOW PORTFOLIO',title:'A portfolio that behaves like a network',body:'The portfolio turns navigation into the interface: nodes expand, ancestors remain visible, paths trace the journey and terminal nodes explain the work behind each part of the system.',tags:['React','TypeScript','Vite','Tailwind CSS']},
 photography:{eyebrow:'PROJECT / GHOUL PHOTOGRAPHY',title:'A cinematic archive',body:'A responsive photography archive focused on visual discovery, with automated content workflows connecting Gemini AI and the Instagram API.',tags:['HTML5','CSS3','JavaScript','Gemini AI','Instagram API'],links:[{label:'OPEN PROJECT',href:'https://ghoul-photography.vercel.app/'}]},
 pylauncher:{eyebrow:'PROJECT / PYLAUNCHER',title:'Python utility project',body:'A Python-based utility branch focused on a practical launcher and desktop interaction experience.',tags:['Python','Launcher','Desktop']},
 experience:{eyebrow:'NAYAN / EXPERIENCE',title:'Engineering in practice',body:'Professional experience combines technical compliance documentation, tender proposals, customer support, shift operations, SAP/HMI workflows, root-cause analysis and quality improvement.',tags:['Analyser Instrument Company','Ashok Leyland','Technical proposals','Quality']},
 skills:{eyebrow:'NAYAN / SKILLS',title:'A practical technical stack',body:'The skill graph covers the languages, frameworks, tools, platforms and web practices actually listed in the professional profile, with each technology now independently explorable.',tags:['Python','JavaScript','HTML5','CSS3','Node.js','FastAPI','GitHub','REST APIs','Responsive Web']},
 philosophy:{eyebrow:'NAYAN / PHILOSOPHY',title:'Think. Build. Ship.',body:'My development philosophy combines an engineering habit of finding the root cause with a developer habit of building the complete system. I value working software, clear documentation, useful feedback and leverage from modern AI-assisted tools.',tags:['Root cause','Systems thinking','Working software','Documentation','Iteration','Leverage']},
 contact:{eyebrow:'NAYAN / CONTACT',title:'Open a connection',body:'Professional contact information is intentionally part of the network. Choose a channel to reveal the direct action, or explore location and availability context before reaching out.',tags:['Email','Phone','LinkedIn','GitHub','Sagar, MP','Professional opportunities']},
 about:{eyebrow:'NAYAN / ABOUT',title:'Engineer at the core',body:'I am a self-taught developer with a Bachelor of Technology in Electrical Engineering. My background spans manufacturing operations and technical proposal work, while my current direction is building complete web products. I bring engineering discipline to software: understand the problem, document the process, build the system and improve it.',tags:['B.Tech Electrical Engineering','Self-taught developer','Manufacturing','Technical proposals','Web Development','India']}
};

const leafDetails:Record<string,Detail>={
 'jp-problem':{eyebrow:'JOBPILOT / PROBLEM',title:'The problem',body:'Job searching and outreach can become repetitive when discovery, matching, drafting, approval and sending are handled separately. This branch turns that work into one connected workflow.',tags:['Workflow','Job search','Automation']},
 'jp-system':{eyebrow:'JOBPILOT / SYSTEM',title:'The workflow',body:'The system is organized around import, matching, drafting, approval and outreach so each stage has a clear place in the overall process.',tags:['Import','Matching','Drafting','Approval','Outreach']},
 'jp-tech':{eyebrow:'JOBPILOT / TECHNOLOGY',title:'Technology direction',body:'A modern web stack and AI-assisted workflow architecture are used to keep the product practical, maintainable and focused on end-to-end delivery.',tags:['Next.js','TypeScript','AI']},
 'jp-next':{eyebrow:'JOBPILOT / NEXT.JS',title:'Next.js',body:'Used as the application framework for structuring and delivering the web experience.',tags:['Next.js','React']},
 'jp-typescript':{eyebrow:'JOBPILOT / TYPESCRIPT',title:'TypeScript',body:'Provides typed application code for safer iteration and maintainability.',tags:['TypeScript','Maintainability']},
 'jp-ai':{eyebrow:'JOBPILOT / AI AGENT',title:'AI as leverage',body:'The AI layer supports the goal of reducing repetitive work while keeping the workflow structured and reviewable.',tags:['AI','Automation','Workflow']},
 'jp-api':{eyebrow:'JOBPILOT / APIS',title:'API layer',body:'APIs connect the different workflow stages and services so the product can operate as a system rather than isolated screens.',tags:['REST APIs','Integrations']},
 'ia-fitness':{eyebrow:'IRON AKHADA / FITNESS',title:'What I built and why',body:'I built Iron Akhada as a web-based fitness radio experience rather than a conventional fitness page. The goal was to combine training-focused discovery with an immersive listening experience.',tags:['Next.js','React','TypeScript','Cloudflare','Fitness radio']},
 'ia-journey':{eyebrow:'IRON AKHADA / USER JOURNEY',title:'How the experience works',body:'The journey is organized around entering the experience, discovering training stations, listening to streamed audio and seeing live listener presence.',tags:['User journey','Training stations','Streamed audio','Live presence']},
 'ia-build':{eyebrow:'IRON AKHADA / BUILD',title:'How it was built',body:'The implementation focuses on a responsive web experience and keeps the interface connected to the core listening and training functions.',tags:['Responsive UI','Next.js','React','TypeScript']},
 'ia-audio':{eyebrow:'IRON AKHADA / STREAMED AUDIO',title:'The listening function',body:'Streamed audio is a central function of the experience, turning the site into a fitness radio rather than a static information page.',tags:['Streaming','Audio','Fitness radio']},
 'ia-presence':{eyebrow:'IRON AKHADA / LIVE PRESENCE',title:'Listener presence',body:'Live listener presence adds a sense of shared activity to the experience and makes the product feel active rather than static.',tags:['Live presence','Interaction']},
 'ia-stations':{eyebrow:'IRON AKHADA / TRAINING STATIONS',title:'Training stations',body:'Training stations organize the fitness experience into focused destinations that support discovery and movement through the product.',tags:['Training','Navigation','Fitness']},
 'pf-flow':{eyebrow:'PORTFOLIO / FLOW',title:'The navigation idea',body:'The portfolio is deliberately built as a connected flow. Navigation is not a separate menu; the graph itself explains how the work is related.',tags:['Network UI','React','TypeScript']},
 'pf-interactive':{eyebrow:'PORTFOLIO / INTERACTIVE',title:'Interaction system',body:'Visitors can drag, pan, zoom, hover and click. The active path and ancestry remain visible while moving deeper.',tags:['Drag','Pan','Zoom','Hover','Click']},
 'pf-phases':{eyebrow:'PORTFOLIO / PHASES',title:'Phased development',body:'The portfolio was built through foundation, interaction, deep flows and polishing phases rather than as one large rewrite.',tags:['Phase 1','Phase 2','Phase 3','Phase 4','Phase 5']},
 'pf-responsive':{eyebrow:'PORTFOLIO / RESPONSIVE',title:'Responsive behavior',body:'The network is designed to remain usable across desktop and mobile viewing rather than treating mobile as an afterthought.',tags:['Mobile','Desktop','Responsive']},
 'pf-trace':{eyebrow:'PORTFOLIO / TRACE',title:'Path tracing',body:'The trace shows where the visitor is inside the hierarchy, keeping the portfolio feeling like one connected system.',tags:['Trace','Hierarchy','Navigation']},
 'pf-access':{eyebrow:'PORTFOLIO / ACCESSIBILITY',title:'Keyboard interaction',body:'Keyboard focus, arrow navigation, Enter activation and Escape-to-home provide a non-pointer route through the network.',tags:['Keyboard','Focus','Accessibility']},
 'gp-archive':{eyebrow:'GHOUL / ARCHIVE',title:'The visual goal',body:'A cinematic photography archive focused on visual discovery instead of a conventional content grid.',tags:['Photography','HTML5','CSS3','JavaScript']},
 'gp-gallery':{eyebrow:'GHOUL / GALLERY',title:'Gallery approach',body:'Responsive galleries make the visual archive usable across different screen sizes.',tags:['Responsive','Gallery','Visual browsing']},
 'gp-automation':{eyebrow:'GHOUL / AUTOMATION',title:'Content workflow',body:'Gemini AI and the Instagram API are part of the automated content workflow around the photography archive.',tags:['Gemini AI','Instagram API','Automation']},
 'gp-responsive':{eyebrow:'GHOUL / RESPONSIVE',title:'Responsive presentation',body:'The archive is designed so the photography remains the focus on different viewport sizes.',tags:['Responsive design','Visual UI']},
 'gp-content':{eyebrow:'GHOUL / CONTENT',title:'Repeatable publishing',body:'The content workflow is designed around repeatability, connecting the archive with automated content operations.',tags:['Content workflow','Automation']},
 'pl-python':{eyebrow:'PYLAUNCHER / PYTHON',title:'Python',body:'Python is the language foundation of the utility project and part of the broader development stack.',tags:['Python','Application development']},
 'pl-launcher':{eyebrow:'PYLAUNCHER / LAUNCHER',title:'Launcher',body:'The launcher branch represents a practical utility-oriented desktop experience.',tags:['Launcher','Utility','Desktop']},
 'pl-interface':{eyebrow:'PYLAUNCHER / INTERFACE',title:'Interface',body:'The interface work centers on desktop interaction and usability.',tags:['Desktop','Usability']},
 'pl-utility':{eyebrow:'PYLAUNCHER / UTILITY',title:'Practical function',body:'The project is kept focused on a useful desktop workflow rather than decorative complexity.',tags:['Utility','Workflow']},
 'ex-engineering':{eyebrow:'EXPERIENCE / ANALYSER',title:'Engineer — Analyser Instrument Company',body:'Prepared and reviewed technical compliance documentation, collaborated on technical proposals, supported customers with product specifications and achieved 90% technical scoring on tender submissions.',tags:['Technical proposals','Documentation','Customer support','90% technical scoring']},
 'ex-manufacturing':{eyebrow:'EXPERIENCE / ASHOK LEYLAND',title:'Graduate Apprentice Trainee',body:'Led shift operations for a 100+ person team using SAP NetWeaver and Siemens HMI, applied root-cause analysis to customer complaints and implemented enhanced inspection measures.',tags:['SAP NetWeaver','Siemens HMI','Shift operations','Quality']},
 'ex-proposals':{eyebrow:'EXPERIENCE / TECHNICAL PROPOSALS',title:'Technical proposals',body:'Prepared and reviewed compliance documentation against tender specifications and customer requirements while collaborating across teams.',tags:['Compliance','Tenders','Documentation']},
 'ex-support':{eyebrow:'EXPERIENCE / CUSTOMER SUPPORT',title:'Technical support',body:'Supported customers by resolving technical queries and clarifying product specifications.',tags:['Customer support','Specifications']},
 'ex-operations':{eyebrow:'EXPERIENCE / SHIFT OPERATIONS',title:'Shift operations',body:'Led operations for a 100+ person team using SAP NetWeaver and Siemens HMI to monitor processes and minimize downtime.',tags:['SAP NetWeaver','Siemens HMI','Operations']},
 'ex-quality':{eyebrow:'EXPERIENCE / QUALITY',title:'Quality improvement',body:'Applied root-cause analysis to customer complaints and implemented enhanced inspection measures to reduce rejection rates and improve product quality.',tags:['Root cause','Inspection','Quality improvement']},
 'sk-javascript':{eyebrow:'SKILLS / JAVASCRIPT',title:'JavaScript',body:'A core language across the web development work and interactive experiences.',tags:['JavaScript','Web Development']},
 'sk-react':{eyebrow:'SKILLS / REACT',title:'React',body:'Used to build interactive web experiences and the connected Flow portfolio.',tags:['React','Interactive UI']},
 'sk-htmlcss':{eyebrow:'SKILLS / HTML + CSS',title:'HTML5 + CSS3',body:'The structural and styling foundation for responsive web interfaces.',tags:['HTML5','CSS3','Responsive']},
 'sk-python':{eyebrow:'SKILLS / PYTHON',title:'Python',body:'Used for application development and the Python utility project.',tags:['Python','Kivy','FastAPI']},
 'sk-fastapi':{eyebrow:'SKILLS / FASTAPI',title:'FastAPI',body:'Part of the Python toolkit for API-oriented development.',tags:['FastAPI','Python','REST APIs']},
 'sk-node':{eyebrow:'SKILLS / NODE.JS',title:'Node.js',body:'Part of the JavaScript web development toolkit.',tags:['Node.js','JavaScript']},
 'sk-rest':{eyebrow:'SKILLS / REST APIS',title:'REST APIs',body:'Used for API-driven product development and integrations.',tags:['REST APIs','Integrations']},
 'sk-git':{eyebrow:'SKILLS / GIT + GITHUB',title:'Git and GitHub',body:'Used for source control, collaboration and maintaining project delivery.',tags:['Git','GitHub','Version control']},
 'sk-actions':{eyebrow:'SKILLS / GITHUB ACTIONS',title:'GitHub Actions',body:'Used for repository automation and continuous verification workflows.',tags:['GitHub Actions','CI']},
 'sk-responsive':{eyebrow:'SKILLS / RESPONSIVE WEB',title:'Responsive web design',body:'Responsive design keeps web experiences usable across desktop and mobile.',tags:['Responsive','Mobile','Desktop']},
 'sk-bootstrap':{eyebrow:'SKILLS / BOOTSTRAP',title:'Bootstrap',body:'A web UI toolkit included in the professional technical skill set.',tags:['Bootstrap','Web UI']},
 'sk-deploy':{eyebrow:'SKILLS / DEPLOYMENT',title:'Netlify / Render',body:'Hands-on deployment experience includes Netlify and Render, with GitHub Pages also listed in the profile.',tags:['Netlify','Render','GitHub Pages']},
 'sk-formspree':{eyebrow:'SKILLS / FORMSPREE',title:'Formspree',body:'Part of the tools and platform experience for web forms and integrations.',tags:['Formspree','Forms','Web']},
 'sk-search':{eyebrow:'SKILLS / SEARCH CONSOLE',title:'Google Search Console',body:'Part of the listed tools and platforms experience for web visibility and site management.',tags:['Google Search Console','Web']},
 'ph-root':{eyebrow:'PHILOSOPHY / FIND THE ROOT',title:'Root-cause first',body:'The engineering habit is to understand the underlying problem before adding complexity.',tags:['Root cause','Engineering']},
 'ph-system':{eyebrow:'PHILOSOPHY / BUILD THE SYSTEM',title:'End-to-end thinking',body:'Think through frontend, backend, deployment and workflow as one system.',tags:['Frontend','Backend','Deployment','Workflow']},
 'ph-leverage':{eyebrow:'PHILOSOPHY / SHIP WITH LEVERAGE',title:'Use leverage',body:'AI-assisted development is a force multiplier for speed, provided the output remains useful and reviewable.',tags:['AI','Leverage','Shipping']},
 'ph-working':{eyebrow:'PHILOSOPHY / WORKING SOFTWARE',title:'Working software wins',body:'The goal is practical, functioning software. A beautiful idea that never ships is still just an idea.',tags:['Delivery','Practicality','Software']},
 'ph-document':{eyebrow:'PHILOSOPHY / DOCUMENT',title:'Make the system understandable',body:'Clear documentation turns technical work into something teams can review, maintain and build upon.',tags:['Documentation','Clarity','Collaboration']},
 'ph-improve':{eyebrow:'PHILOSOPHY / KEEP IMPROVING',title:'Iterate deliberately',body:'Testing, feedback and iteration are used to find weak points and strengthen the final product.',tags:['Testing','Feedback','Iteration']},
 'ct-email':{eyebrow:'CONTACT / EMAIL',title:'Email',body:'The primary direct channel for professional communication.',tags:['nayanasati2001@gmail.com'],links:[{label:'SEND EMAIL',href:'mailto:nayanasati2001@gmail.com'}]},
 'ct-linkedin':{eyebrow:'CONTACT / LINKEDIN',title:'LinkedIn',body:'Professional profile and network.',tags:['LinkedIn'],links:[{label:'OPEN LINKEDIN',href:'https://linkedin.com/in/nayan-1209-asati'}]},
 'ct-github':{eyebrow:'CONTACT / GITHUB',title:'GitHub',body:'Code, experiments and repositories.',tags:['GitHub'],links:[{label:'OPEN GITHUB',href:'https://github.com/Nayan1209'}]},
 'ct-phone':{eyebrow:'CONTACT / PHONE',title:'Phone',body:'Direct phone contact for professional communication.',tags:['+91 6262055238'],links:[{label:'CALL / DIAL',href:'tel:+916262055238'}]},
 'ct-location':{eyebrow:'CONTACT / LOCATION',title:'Sagar, Madhya Pradesh',body:'Based in Sagar, Madhya Pradesh, India.',tags:['Sagar','Madhya Pradesh','India']},
 'ct-open':{eyebrow:'CONTACT / OPEN TO',title:'Professional conversations',body:'Open the conversation around engineering, web development, technical problem solving and software opportunities.',tags:['Engineering','Web Development','Software']},
 'ab-engineer':{eyebrow:'ABOUT / ENGINEER',title:'Engineering foundation',body:'Electrical engineering is the academic foundation behind the practical approach to problem solving, process thinking and technical analysis.',tags:['Electrical Engineering','B.Tech']},
 'ab-developer':{eyebrow:'ABOUT / DEVELOPER',title:'Self-taught developer',body:'The development path is self-taught and focused on building complete products across frontend, backend and deployment.',tags:['Frontend','Backend','Deployment']},
 'ab-education':{eyebrow:'ABOUT / EDUCATION',title:'B.Tech Electrical Engineering',body:'Bachelor of Technology in Electrical Engineering from Gurukul Kangri Vishwavidyalaya, Haridwar, completed in May 2024 with a final grade of 70.57%.',tags:['B.Tech','Electrical Engineering','70.57%']},
 'ab-certifications':{eyebrow:'ABOUT / CERTIFICATIONS',title:'Learning beyond the degree',body:'Certifications and training include a CSS, Bootstrap, JavaScript & PHP stack course, an AI Tools Workshop and an Ashok Leyland manufacturing apprenticeship.',tags:['Web development','AI Tools','Manufacturing']},
 'ab-languages':{eyebrow:'ABOUT / LANGUAGES',title:'Hindi + English',body:'Hindi is native and English is professional, supporting communication across technical and professional settings.',tags:['Hindi','English']},
 'ab-location':{eyebrow:'ABOUT / LOCATION',title:'Sagar, Madhya Pradesh',body:'Based in Sagar, Madhya Pradesh, India.',tags:['India','Madhya Pradesh']},
 'ab-approach':{eyebrow:'ABOUT / APPROACH',title:'Engineering discipline + software delivery',body:'The common thread is practical problem solving: understand the root cause, build the system, document it, ship it and improve it.',tags:['Root cause','Systems thinking','Delivery','Iteration']}
};

export default function Home(){
 const [level,setLevel]=useState<Level>('home'),[scale,setScale]=useState(1),[pan,setPan]=useState<Point>({x:0,y:0}),[hovered,setHovered]=useState<string|null>(null),[selected,setSelected]=useState('nayan'),[selectedDetailId,setSelectedDetailId]=useState<string|null>(null),[dragging,setDragging]=useState(false),[opening,setOpening]=useState(false),[focusIndex,setFocusIndex]=useState(0);
 const stage=useRef<HTMLDivElement>(null),dragStart=useRef<Point>({x:0,y:0}),panStart=useRef<Point>({x:0,y:0}),velocity=useRef<Point>({x:0,y:0}),animation=useRef<number|null>(null);
 const graph=graphFor(level);
 const ancestry=useMemo<Level[]>(()=>{const chain:Level[]=[];let cursor:Level=level;while(cursor!=='home'){chain.unshift(cursor);cursor=parentOf[cursor]??'home';}return ['home',...chain]},[level]);
 const depth=ancestry.length-1;
 const ancestorNodes=useMemo(()=>ancestry.map((item,index)=>{const node=nodeFor(item),distance=depth-index;return {...node,x:-120+distance*240,y:0,size:distance===0?node.size:Math.max(54,(node.size??100)*Math.pow(.78,distance)),depth:distance}}),[ancestry,depth]);
 const nested=level!=='home';
 const focus=nested?ancestorNodes[depth]:graph.center;
 const displayNodes=useMemo(()=>{if(!nested){const primary=graph.nodes.filter(x=>x.homeRole==='primary'),satellites=graph.nodes.filter(x=>x.homeRole==='satellite');const primaryPos:Record<string,Point>={projects:{x:-230,y:-80},experience:{x:0,y:-220},skills:{x:230,y:-80},philosophy:{x:-210,y:190},contact:{x:210,y:190},about:{x:0,y:250}};const satellitePos:Record<string,Point>={jobpilot:{x:-355,y:-120},ironakhada:{x:-330,y:-5},portfolio:{x:-270,y:-185},photography:{x:-180,y:-150},pylauncher:{x:-180,y:-25},engineering:{x:-80,y:-305},manufacturing:{x:20,y:-315},proposal:{x:120,y:-300}};return [...primary.map(x=>({...x,...primaryPos[x.id]})),...satellites.map(x=>({...x,...satellitePos[x.id]}))]}
 const count=graph.nodes.length;const pos=(i:number):Point=>{if(count===1)return{x:285,y:0};if(count===2)return{x:285,y:i===0?-120:120};if(count===3)return i===1?{x:360,y:0}:{x:275,y:i===0?-145:145};const cols=Math.min(3,Math.ceil(count/3)),col=i%cols,row=Math.floor(i/cols),rows=Math.ceil(count/cols);return{x:250+col*155,y:(row-(rows-1)/2)*125};};return graph.nodes.map((node,i)=>{const p=pos(i);return {...node,x:focus.x+p.x,y:p.y}})},[graph,nested,focus.x]);
 const allNodes=nested?[...ancestorNodes,...displayNodes]:[graph.center,...displayNodes];
 const activeId=hovered??selected,activeNode=allNodes.find(x=>x.id===activeId),detail=selectedDetailId&&leafDetails[selectedDetailId]?leafDetails[selectedDetailId]:details[level];
 const trace=ancestry.map(x=>x==='home'?'NAYAN ASATI':labels[x]);
 const setLevelView=(next:Level)=>{const nextDepth=next==='home'?0:next==='projects'?1:Math.min(3,depth+1);setLevel(next);setScale(Math.max(.68,1-nextDepth*.055));setPan({x:0,y:0});setHovered(null);setSelectedDetailId(null);setSelected(next==='home'?'nayan':nodeFor(next).id);setFocusIndex(0);velocity.current={x:0,y:0}};
 const resetView=(next:Level='home')=>setLevelView(next);
 const zoom=(factor:number,origin?:Point)=>setScale(current=>{const next=Math.min(2.65,Math.max(.58,current*factor));if(origin){const ratio=next/current;setPan(p=>({x:origin.x-(origin.x-p.x)*ratio,y:origin.y-(origin.y-p.y)*ratio}))}return next});
 const selectNode=(node:Node)=>{if(node.id==='nayan'){resetView('home');return}const ancestor=ancestry.find(x=>x!=='home'&&nodeFor(x).id===node.id);if(ancestor){setLevelView(ancestor);return}setSelected(node.id);const next=childLinks[node.id];if(next&&next!=='home'){setOpening(true);setSelectedDetailId(null);setLevel(next);setScale(Math.max(.68,1-(ancestry.length)*.055));setPan({x:0,y:0});setHovered(null);window.setTimeout(()=>setOpening(false),720);return}setSelectedDetailId(node.id)};
 const focusNode=(index:number)=>{const safe=((index%allNodes.length)+allNodes.length)%allNodes.length;setFocusIndex(safe);setSelected(allNodes[safe].id);setHovered(allNodes[safe].id)};
 const onWheel=(e:React.WheelEvent<HTMLDivElement>)=>{e.preventDefault();const rect=stage.current?.getBoundingClientRect(),origin=rect?{x:e.clientX-(rect.left+rect.width/2),y:e.clientY-(rect.top+rect.height/2)}:undefined;zoom(e.deltaY<0?1.075:.93,origin)};
 const onPointerDown=(e:React.PointerEvent<HTMLDivElement>)=>{if((e.target as Element).closest('[data-node]')||(e.target as Element).closest('button')||(e.target as Element).closest('a'))return;setDragging(true);dragStart.current={x:e.clientX,y:e.clientY};panStart.current=pan;velocity.current={x:0,y:0};stage.current?.setPointerCapture(e.pointerId)};
 const onPointerMove=(e:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const dx=e.clientX-dragStart.current.x,dy=e.clientY-dragStart.current.y;setPan({x:panStart.current.x+dx,y:panStart.current.y+dy});velocity.current={x:dx*.045,y:dy*.045}};
 const stopDrag=()=>{setDragging(false);if(animation.current)cancelAnimationFrame(animation.current);const coast=()=>{velocity.current.x*=.91;velocity.current.y*=.91;if(Math.abs(velocity.current.x)+Math.abs(velocity.current.y)<.15)return;setPan(p=>({x:p.x+velocity.current.x,y:p.y+velocity.current.y}));animation.current=requestAnimationFrame(coast)};animation.current=requestAnimationFrame(coast)};
 useEffect(()=>()=>{if(animation.current)cancelAnimationFrame(animation.current)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')resetView('home');if(e.key==='+'||e.key==='=')zoom(1.08);if(e.key==='-')zoom(.925);if(e.key==='0')resetView(level);if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();focusNode(focusIndex+1)}if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();focusNode(focusIndex-1)}if(e.key==='Enter'){const node=allNodes[focusIndex];if(node)selectNode(node)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[level,focusIndex,allNodes]);
 const primary=displayNodes.filter(x=>x.homeRole==='primary'),projectHome=displayNodes.filter(x=>['jobpilot','ironakhada','portfolio','photography','pylauncher'].includes(x.id)),experienceHome=displayNodes.filter(x=>['engineering','manufacturing','proposal'].includes(x.id));
 return <main className="flow" ref={stage} onWheel={onWheel} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={stopDrag} onPointerCancel={stopDrag}>
  <div className="flow-grid"/><div className="flow-vignette"/>
  <header className="flow-header"><button className="flow-wordmark" onClick={()=>resetView('home')} aria-label="Return home">FLOW<span>.</span></button><div className="flow-header-meta"><span>PORTFOLIO / 05</span><span>FLOW NETWORK</span></div></header>
  <div className="flow-trace" aria-label="Current navigation path">{trace.map((item,i)=><span key={`${item}-${i}`} className={i===trace.length-1?'current':''}>{item}{i<trace.length-1&&<b>→</b>}</span>)}</div>
  <section className={`flow-stage ${dragging?'is-dragging':''} ${opening?'is-opening':''}`} aria-label="Nayan Asati interactive portfolio network"><div className="flow-world" style={{transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${scale})`}}>
   <svg className="flow-lines" viewBox="-620 -410 1240 820" aria-hidden="true">
    {nested&&ancestorNodes.slice(1).map((node,i)=>{const prev=ancestorNodes[i];return <line key={`ancestor-${node.id}`} className={activeId===node.id||activeId===prev.id?'active':''} x1={prev.x} y1={prev.y} x2={node.x} y2={node.y}/>})}
    {!nested&&primary.map(node=><line key={`primary-${node.id}`} className={activeId===node.id||activeId==='nayan'?'active':''} x1={focus.x} y1={focus.y} x2={node.x} y2={node.y}/>)}
    {!nested&&projectHome.map(node=>{const parent=primary.find(x=>x.id==='projects');return parent&&<line key={`project-${node.id}`} className={activeId===node.id||activeId==='projects'?'active':''} x1={parent.x} y1={parent.y} x2={node.x} y2={node.y}/>})}
    {!nested&&experienceHome.map(node=>{const parent=primary.find(x=>x.id==='experience');return parent&&<line key={`experience-${node.id}`} className={activeId===node.id||activeId==='experience'?'active':''} x1={parent.x} y1={parent.y} x2={node.x} y2={node.y}/>})}
    {nested&&displayNodes.map(node=><line key={node.id} className={activeId===node.id||activeId===focus.id?'active':''} x1={focus.x} y1={focus.y} x2={node.x} y2={node.y}/>)}
   </svg>
   {allNodes.map((node,index)=><button key={`${node.id}-${index}`} data-node className={`flow-node ${node.id===focus.id?'center focus-center':''} ${node.homeRole==='primary'?'home-primary':''} ${node.homeRole==='satellite'?'home-satellite':''} ${node.depth?`ancestor-depth-${node.depth}`:''} ${node.id==='nayan'?'root-persistent':''} ${activeId===node.id?'active':''}`} style={{left:`calc(50% + ${node.x}px)`,top:`calc(50% + ${node.y}px)`,'--node-size':`${node.size??70}px`} as React.CSSProperties} onClick={()=>selectNode(node)} onMouseEnter={()=>{setHovered(node.id);setSelected(node.id)}} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(node.id)} onBlur={()=>setHovered(null)} aria-label={node.id==='nayan'?'Return home':`Explore ${node.label}`}><span className="node-halo"/><span className="node-core">{node.displayLabel??node.label}</span>{node.description&&<span className="node-description">{node.description}</span>}</button>)}
  </div></section>
  <aside className={`flow-detail phase4-detail ${selectedDetailId?'is-case-study':''}`} aria-live="polite"><span>{detail.eyebrow}</span><h1>{detail.title}</h1><p>{detail.body}</p><div className="detail-tags">{detail.tags.map(tag=><span key={tag}>{tag}</span>)}</div>{detail.links&&detail.links.length>0&&<div className="detail-links">{detail.links.map(link=><a key={link.href} href={link.href} target="_blank" rel="noreferrer">{link.label} <ExternalLink size={12}/></a>)}</div>}{selectedDetailId&&<small className="detail-hint">CASE STUDY NODE · CLICK ANOTHER NODE TO CONTINUE</small>}</aside>
  <aside className="flow-path" aria-label="Path status"><span>TRACE</span><strong>{activeNode?.label??labels[level]}</strong><small>{level==='home'?'ROOT NODE':`DEPTH ${depth} · ANCESTRY VISIBLE`}</small></aside>
  <aside className="flow-controls" aria-label="Network controls">{level!=='home'&&<button onClick={()=>resetView('home')} aria-label="Back to home"><ArrowLeft size={14}/></button>}<button onClick={()=>zoom(.9)} aria-label="Zoom out"><Minus size={14}/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>zoom(1.1)} aria-label="Zoom in"><Plus size={14}/></button><button onClick={()=>resetView(level)} aria-label="Reset view"><RotateCcw size={14}/></button><button onClick={()=>{setPan({x:0,y:0});setScale(level==='home'?1:Math.max(.68,1-depth*.055))}} aria-label="Center network"><LocateFixed size={14}/></button></aside>
  <footer className="flow-footer"><div><small>FLOW PORTFOLIO</small><strong>CINEMATIC NAVIGATION</strong></div><div className="flow-status">{level==='home'?'HOME / 06 CONNECTIONS':`${homeGraph.center.label} / ${graph.nodes.length} FOCUS NODES`}</div><div className="flow-footer-right">ESC / HOME · ARROWS / TRACE</div></footer>
 </main>;
}
