'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ExternalLink, LocateFixed, Minus, Plus, RotateCcw } from 'lucide-react';

type Level = 'home'|'projects'|'jobpilot'|'ironakhada'|'portfolio'|'photography'|'pylauncher'|'experience'|'skills'|'philosophy'|'contact'|'about';
type Point = { x:number; y:number };
type Node = { id:string; label:string; description?:string; href?:string; size?:number; child?:Level };
type Detail = { eyebrow:string; title:string; body:string; tags:string[]; links?:{label:string;href:string}[] };

const labels:Record<Level,string>={home:'HOME',projects:'PROJECTS',jobpilot:'JOBPILOT AI',ironakhada:'IRON AKHADA',portfolio:'PORTFOLIO',photography:'GHOUL PHOTOGRAPHY',pylauncher:'PYLAUNCHER',experience:'EXPERIENCE',skills:'SKILLS',philosophy:'PHILOSOPHY',contact:'CONTACT',about:'ABOUT'};
const parent:Partial<Record<Level,Level>>={projects:'home',jobpilot:'projects',ironakhada:'projects',portfolio:'projects',photography:'projects',pylauncher:'projects',experience:'home',skills:'home',philosophy:'home',contact:'home',about:'home'};

const children:Record<Level,Node[]>={
 home:[
  {id:'projects',label:'PROJECTS',size:96,child:'projects'},{id:'experience',label:'EXPERIENCE',size:96,child:'experience'},{id:'skills',label:'SKILLS',size:96,child:'skills'},{id:'philosophy',label:'PHILOSOPHY',size:96,child:'philosophy'},{id:'contact',label:'CONTACT',size:96,child:'contact'},{id:'about',label:'ABOUT',size:96,child:'about'},
  {id:'jobpilot',label:'JOBPILOT AI',size:58,description:'AI-assisted job outreach',child:'jobpilot'},{id:'ironakhada',label:'IRON AKHADA',size:58,description:'Fitness radio experience',child:'ironakhada'},{id:'portfolio',label:'PORTFOLIO',size:58,description:'Interactive Flow portfolio',child:'portfolio'},{id:'photography',label:'PHOTOGRAPHY',size:58,description:'Cinematic photography archive',child:'photography'},{id:'pylauncher',label:'PYLAUNCHER',size:58,description:'Python utility project',child:'pylauncher'},
  {id:'engineering',label:'ANALYSER',size:58,description:'Engineer · Nov 2025 – Jun 2026'},{id:'manufacturing',label:'ASHOK LEYLAND',size:58,description:'Graduate Apprentice · Aug 2024 – Jul 2025'},{id:'proposal',label:'ROOT-CAUSE',size:58,description:'Engineering problem solving'}
 ],
 projects:[{id:'jobpilot',label:'JOBPILOT AI',description:'AI-assisted job outreach workflow',child:'jobpilot'},{id:'ironakhada',label:'IRON AKHADA',description:'Fitness radio experience',child:'ironakhada'},{id:'portfolio',label:'NAYAN ASATI PORTFOLIO',description:'Interactive Flow portfolio',child:'portfolio'},{id:'photography',label:'GHOUL PHOTOGRAPHY',description:'Cinematic photography archive',child:'photography'},{id:'pylauncher',label:'PYLAUNCHER',description:'Python utility project',child:'pylauncher'}],
 jobpilot:[{id:'jp-problem',label:'PROBLEM',description:'Reduce repetitive job-search and outreach work.'},{id:'jp-system',label:'SYSTEM',description:'Import, matching, drafting, approval and outreach.'},{id:'jp-tech',label:'TECHNOLOGY',description:'Modern web stack with AI-assisted workflows.'},{id:'jp-next',label:'NEXT.JS',description:'Application framework.'},{id:'jp-typescript',label:'TYPESCRIPT',description:'Typed application foundation.'},{id:'jp-ai',label:'AI AGENT',description:'Automation layer.'},{id:'jp-api',label:'APIS',description:'Connect workflow stages and services.'}],
 ironakhada:[{id:'ia-fitness',label:'FITNESS',description:'Fitness-focused product direction.'},{id:'ia-journey',label:'USER JOURNEY',description:'Entering, discovering and training.'},{id:'ia-build',label:'BUILD',description:'Responsive product implementation.'},{id:'ia-audio',label:'STREAMED AUDIO',description:'Core listening function.'},{id:'ia-presence',label:'LIVE PRESENCE',description:'Listener presence in the experience.'},{id:'ia-stations',label:'TRAINING STATIONS',description:'Training-focused navigation.'}],
 portfolio:[{id:'pf-flow',label:'FLOW',description:'Portfolio navigation as a connected system.'},{id:'pf-interactive',label:'INTERACTIVE',description:'Drag, zoom, hover and click.'},{id:'pf-phases',label:'PHASES',description:'Foundation through polish.'},{id:'pf-responsive',label:'RESPONSIVE',description:'Desktop and mobile experience.'},{id:'pf-trace',label:'TRACE',description:'Path-aware navigation.'},{id:'pf-access',label:'ACCESSIBILITY',description:'Keyboard and focus interaction.'}],
 photography:[{id:'gp-archive',label:'ARCHIVE',description:'Cinematic photography archive.'},{id:'gp-gallery',label:'GALLERY',description:'Responsive visual browsing.'},{id:'gp-automation',label:'AUTOMATION',description:'Gemini AI and Instagram API workflows.'},{id:'gp-responsive',label:'RESPONSIVE',description:'Visual experience across screen sizes.'},{id:'gp-content',label:'CONTENT',description:'Repeatable content workflow.'}],
 pylauncher:[{id:'pl-python',label:'PYTHON',description:'Python application development.'},{id:'pl-launcher',label:'LAUNCHER',description:'Utility-oriented launcher experience.'},{id:'pl-interface',label:'INTERFACE',description:'Desktop interaction and usability.'},{id:'pl-utility',label:'UTILITY',description:'Practical desktop workflow.'}],
 experience:[{id:'ex-engineering',label:'ENGINEER',description:'Analyser Instrument Company · Nov 2025 – Jun 2026'},{id:'ex-manufacturing',label:'ASHOK LEYLAND',description:'Graduate Apprentice Trainee · Aug 2024 – Jul 2025'},{id:'ex-proposals',label:'TECHNICAL PROPOSALS',description:'Compliance documentation and tender proposals.'},{id:'ex-support',label:'CUSTOMER SUPPORT',description:'Product specifications and technical queries.'},{id:'ex-operations',label:'SHIFT OPERATIONS',description:'100+ person team, SAP NetWeaver and Siemens HMI.'},{id:'ex-quality',label:'QUALITY',description:'Root-cause analysis and enhanced inspection measures.'}],
 skills:[{id:'sk-javascript',label:'JAVASCRIPT',description:'Core web language.'},{id:'sk-react',label:'REACT',description:'Interactive UI development.'},{id:'sk-htmlcss',label:'HTML / CSS',description:'Web structure and styling.'},{id:'sk-python',label:'PYTHON',description:'Application development.'},{id:'sk-fastapi',label:'FASTAPI',description:'Python API development.'},{id:'sk-node',label:'NODE.JS',description:'JavaScript runtime and tooling.'},{id:'sk-rest',label:'REST APIS',description:'API-driven integrations.'},{id:'sk-git',label:'GIT / GITHUB',description:'Source control and delivery.'},{id:'sk-actions',label:'GITHUB ACTIONS',description:'Repository automation and CI.'},{id:'sk-responsive',label:'RESPONSIVE WEB',description:'Mobile and desktop interfaces.'}],
 philosophy:[{id:'ph-root',label:'FIND THE ROOT',description:'Understand the underlying problem first.'},{id:'ph-system',label:'BUILD THE SYSTEM',description:'Think frontend, backend, deployment and workflow together.'},{id:'ph-leverage',label:'SHIP WITH LEVERAGE',description:'Use AI-assisted development to move faster.'},{id:'ph-working',label:'WORKING SOFTWARE',description:'Prefer useful, functioning software.'},{id:'ph-document',label:'DOCUMENT',description:'Make decisions and processes understandable.'},{id:'ph-improve',label:'KEEP IMPROVING',description:'Use feedback, testing and iteration.'}],
 contact:[{id:'ct-email',label:'EMAIL',description:'nayanasati2001@gmail.com',href:'mailto:nayanasati2001@gmail.com'},{id:'ct-linkedin',label:'LINKEDIN',description:'Professional profile.',href:'https://linkedin.com/in/nayan-1209-asati'},{id:'ct-github',label:'GITHUB',description:'Code and repositories.',href:'https://github.com/Nayan1209'},{id:'ct-phone',label:'PHONE',description:'+91 6262055238',href:'tel:+916262055238'},{id:'ct-location',label:'LOCATION',description:'Sagar, Madhya Pradesh, India.'},{id:'ct-open',label:'OPEN TO',description:'Professional conversations and opportunities.'}],
 about:[{id:'ab-engineer',label:'ENGINEER',description:'Electrical engineering foundation.'},{id:'ab-developer',label:'DEVELOPER',description:'Self-taught full-product developer.'},{id:'ab-education',label:'EDUCATION',description:'B.Tech Electrical Engineering.'},{id:'ab-certifications',label:'CERTIFICATIONS',description:'CSS/Bootstrap/JavaScript/PHP, AI Tools Workshop and apprenticeship.'},{id:'ab-languages',label:'LANGUAGES',description:'Hindi native and English professional.'},{id:'ab-location',label:'BASED IN',description:'Sagar, Madhya Pradesh, India.'},{id:'ab-approach',label:'APPROACH',description:'Engineering discipline plus practical software delivery.'}]
};

const details:Record<Level,Detail>={
 home:{eyebrow:'NAYAN / HOME',title:'Engineer → Developer',body:'A self-taught developer building complete products end-to-end, backed by an engineering mindset for root-cause analysis, documentation and problem solving.',tags:['Web Development','Engineering','AI-assisted development']},
 projects:{eyebrow:'NAYAN / PROJECTS',title:'Selected work',body:'Every project is a connected branch. Enter a project to travel deeper without leaving the network.',tags:['JobPilot AI','Iron Akhada','Portfolio','Ghoul Photography','PyLauncher']},
 jobpilot:{eyebrow:'PROJECT / JOBPILOT AI',title:'Job outreach as a system',body:'An AI-assisted job outreach workflow organized around repeatable stages instead of disconnected manual work.',tags:['Next.js','TypeScript','AI','APIs'],links:[{label:'OPEN GITHUB',href:'https://github.com/Nayan1209/jobpilot-ai'}]},
 ironakhada:{eyebrow:'PROJECT / IRON AKHADA',title:'Fitness radio experience',body:'A web-based fitness radio experience with streamed audio, live listener presence, training stations and immersive UI.',tags:['Next.js','React','TypeScript','Cloudflare']},
 portfolio:{eyebrow:'PROJECT / FLOW PORTFOLIO',title:'A portfolio that behaves like a network',body:'Navigation itself is the interface: nodes expand, ancestors remain visible and paths trace the journey.',tags:['React','TypeScript','Vite','Tailwind CSS']},
 photography:{eyebrow:'PROJECT / GHOUL PHOTOGRAPHY',title:'A cinematic archive',body:'A responsive photography archive focused on visual discovery, with automated content workflows.',tags:['HTML5','CSS3','JavaScript','Gemini AI','Instagram API'],links:[{label:'OPEN PROJECT',href:'https://ghoul-photography.vercel.app/'}]},
 pylauncher:{eyebrow:'PROJECT / PYLAUNCHER',title:'Python utility project',body:'A Python-based utility focused on a practical launcher and desktop interaction experience.',tags:['Python','Launcher','Desktop']},
 experience:{eyebrow:'NAYAN / EXPERIENCE',title:'Engineering in practice',body:'Professional experience combines technical proposals, customer support, shift operations, SAP/HMI workflows, root-cause analysis and quality improvement.',tags:['Analyser Instrument Company','Ashok Leyland','Technical proposals','Quality']},
 skills:{eyebrow:'NAYAN / SKILLS',title:'A practical technical stack',body:'Languages, frameworks, tools, platforms and web practices are independently explorable in this branch.',tags:['JavaScript','Python','React','FastAPI','GitHub','REST APIs']},
 philosophy:{eyebrow:'NAYAN / PHILOSOPHY',title:'Think. Build. Ship.',body:'Find the root, build the system, ship working software, document decisions and keep improving.',tags:['Root cause','Systems thinking','Working software','Iteration']},
 contact:{eyebrow:'NAYAN / CONTACT',title:'Open a connection',body:'Choose a channel to open the relevant action while the network remains the navigation layer.',tags:['Email','Phone','LinkedIn','GitHub']},
 about:{eyebrow:'NAYAN / ABOUT',title:'Engineer at the core',body:'Electrical engineering education, manufacturing experience and self-taught software development come together in one practical approach to solving problems.',tags:['B.Tech Electrical Engineering','Developer','Manufacturing','Web Development']}
};

function pathTo(level:Level){const result:Level[]=[];let current:Level|undefined=level;while(current){result.unshift(current);current=parent[current]}return result}

export default function Home(){
 const [level,setLevel]=useState<Level>('home');
 const [scale,setScale]=useState(1);
 const [camera,setCamera]=useState<Point>({x:0,y:0});
 const [selected,setSelected]=useState('nayan');
 const [hovered,setHovered]=useState<string|null>(null);
 const [dragging,setDragging]=useState(false);
 const [opening,setOpening]=useState(false);
 const stage=useRef<HTMLDivElement>(null);const dragStart=useRef<Point>({x:0,y:0});const cameraStart=useRef<Point>({x:0,y:0});const velocity=useRef<Point>({x:0,y:0});const raf=useRef<number|null>(null);
 const path=useMemo(()=>pathTo(level),[level]);const depth=path.length-1;const activeChildren=children[level];
 const positions=useMemo(()=>{const map=new Map<string,Point>();map.set('nayan',{x:0,y:0});if(level==='home'){[['projects',-210,-90],['experience',0,-205],['skills',210,-90],['philosophy',-185,175],['contact',185,175],['about',0,250],['jobpilot',-315,-145],['ironakhada',-285,-5],['portfolio',-275,115],['photography',275,-5],['pylauncher',285,115],['engineering',-95,-315],['manufacturing',95,-315],['proposal',0,-300]].forEach(([id,x,y])=>map.set(id as string,{x:x as number,y:y as number}));return map;}map.set('nayan',{x:-depth*190,y:0});path.slice(1).forEach((p,i)=>map.set(p,{x:-(depth-i-1)*190,y:0}));const count=activeChildren.length;activeChildren.forEach((n,i)=>{const angle=(-Math.PI*.86)+(i/Math.max(1,count-1))*Math.PI*1.72;const radius=count>6?185:160;map.set(n.id,{x:Math.cos(angle)*radius+42,y:Math.sin(angle)*radius});});return map},[level,depth,path,activeChildren]);
 const visible=useMemo(()=>{const map=new Map<string,Node>();map.set('nayan',{id:'nayan',label:'NAYAN ASATI',size:180});path.slice(1).forEach((p,i)=>map.set(p,{id:p,label:labels[p],size:i===path.length-2?148:88}));activeChildren.forEach(n=>map.set(n.id,n));return [...map.values()]},[path,activeChildren]);
 const openNode=(node:Node)=>{if(node.id==='nayan'){setLevel('home');setSelected('nayan');setScale(1);setCamera({x:0,y:0});return}if(node.child){setOpening(true);setSelected(node.id);setLevel(node.child);setScale(Math.max(.7,1-(pathTo(node.child).length-1)*.08));setCamera({x:0,y:0});window.setTimeout(()=>setOpening(false),420);return}if(node.href)window.open(node.href,'_blank','noopener,noreferrer');setSelected(node.id)};
 const zoom=(factor:number,origin?:Point)=>setScale(current=>{const next=Math.min(2.8,Math.max(.55,current*factor));if(origin){const ratio=next/current;setCamera(c=>({x:origin.x-(origin.x-c.x)*ratio,y:origin.y-(origin.y-c.y)*ratio}))}return next});
 const onWheel=(e:React.WheelEvent<HTMLDivElement>)=>{e.preventDefault();const rect=stage.current?.getBoundingClientRect();if(!rect)return;const local={x:e.clientX-(rect.left+rect.width/2),y:e.clientY-(rect.top+rect.height/2)};const hit=visible.find(n=>{const p=positions.get(n.id);if(!p)return false;const sx=p.x*scale+camera.x,sy=p.y*scale+camera.y;return Math.hypot(local.x-sx,local.y-sy)<((n.size||58)*scale)/2+26});if(hit&&e.deltaY<0){openNode(hit);return}zoom(e.deltaY<0?1.09:.92,local)};
 const onDown=(e:React.PointerEvent<HTMLDivElement>)=>{if((e.target as Element).closest('[data-node]')||(e.target as Element).closest('button')||(e.target as Element).closest('a'))return;setDragging(true);dragStart.current={x:e.clientX,y:e.clientY};cameraStart.current=camera;velocity.current={x:0,y:0};stage.current?.setPointerCapture(e.pointerId)};
 const onMove=(e:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const dx=e.clientX-dragStart.current.x,dy=e.clientY-dragStart.current.y;setCamera({x:cameraStart.current.x+dx,y:cameraStart.current.y+dy});velocity.current={x:dx*.04,y:dy*.04}};
 const onUp=()=>{setDragging(false);if(raf.current)cancelAnimationFrame(raf.current);const coast=()=>{velocity.current.x*=.91;velocity.current.y*=.91;if(Math.abs(velocity.current.x)+Math.abs(velocity.current.y)<.15)return;setCamera(c=>({x:c.x+velocity.current.x,y:c.y+velocity.current.y}));raf.current=requestAnimationFrame(coast)};raf.current=requestAnimationFrame(coast)};
 useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current)},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setLevel('home');setSelected('nayan');setScale(1);setCamera({x:0,y:0})}if(e.key==='+'||e.key==='=')zoom(1.08);if(e.key==='-')zoom(.92)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const activeNode=visible.find(n=>n.id===(hovered||selected));const detail=details[level];
 return <main className="flow" ref={stage} onWheel={onWheel} onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={onUp}>
  <div className="flow-grid"/><div className="flow-vignette"/>
  <header className="flow-header"><button className="flow-wordmark" onClick={()=>openNode({id:'nayan',label:'NAYAN ASATI'})}>FLOW<span>.</span></button><div className="flow-header-meta"><span>PORTFOLIO / 04</span><span>FLOW NETWORK</span></div></header>
  <div className="flow-trace">{path.map((p,i)=><span key={`${p}-${i}`} className={i===path.length-1?'current':''}>{labels[p]}{i<path.length-1&&<b>→</b>}</span>)}</div>
  <section className={`flow-stage ${dragging?'is-dragging':''} ${opening?'is-opening':''}`}>
   <div className="flow-world" style={{transform:`translate3d(${camera.x}px,${camera.y}px,0) scale(${scale})`}}>
    <svg className="flow-lines" viewBox="-600 -430 1200 860" aria-hidden="true">
     {path.slice(1).map((p,i)=>{const a=positions.get(path[i]),b=positions.get(p);return a&&b?<line key={`path-${p}`} className={(hovered===p||selected===p)?'active':''} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}
     {activeChildren.map(n=>{const a=positions.get(level),b=positions.get(n.id);return a&&b?<line key={n.id} className={(hovered===n.id||selected===n.id)?'active':''} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}
     {level==='home'&&[['projects','jobpilot'],['projects','ironakhada'],['projects','portfolio'],['projects','photography'],['projects','pylauncher'],['experience','engineering'],['experience','manufacturing'],['experience','proposal']].map(([aId,bId])=>{const a=positions.get(aId),b=positions.get(bId);return a&&b?<line key={`${aId}-${bId}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}
    </svg>
    {visible.map(node=>{const p=positions.get(node.id)!;const ancestor=path.includes(node.id as Level);const root=node.id==='nayan';const depthScale=root?Math.max(.42,1-depth*.1):ancestor?Math.max(.62,1-(path.indexOf(node.id as Level)-1)*.08):1;return <button data-node key={node.id} className={`flow-node ${root?'root-node':''} ${node.id===level?'focus-center':''} ${ancestor?'ancestor-node':''} ${selected===node.id||hovered===node.id?'active':''}`} style={{left:`calc(50% + ${p.x}px)`,top:`calc(50% + ${p.y}px)`,['--node-size' as string]:`${(node.size||58)*depthScale}px`}} onClick={()=>openNode(node)} onMouseEnter={()=>setHovered(node.id)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(node.id)} onBlur={()=>setHovered(null)} aria-label={`Explore ${node.label}`}><span className="node-halo"/><span className="node-core">{node.label}</span>{node.description&&<span className="node-description">{node.description}</span>}</button>})}
   </div>
  </section>
  {level!=='home'&&<button className="flow-back" onClick={()=>{const p=parent[level]||'home';setLevel(p);setSelected(p==='home'?'nayan':p);setScale(p==='home'?1:.92);setCamera({x:0,y:0})}}><ArrowLeft size={13}/> BACK</button>}
  <aside className="flow-detail"><span>{detail.eyebrow}</span><h1>{activeNode?.label||detail.title}</h1><p>{activeNode?.description||detail.body}</p><div className="detail-tags">{detail.tags.map(t=><span key={t}>{t}</span>)}</div>{detail.links&&<div className="detail-links">{detail.links.map(l=><a key={l.href} href={l.href} target="_blank" rel="noreferrer">{l.label}<ExternalLink size={12}/></a>)}</div>}</aside>
  <aside className="flow-path"><span>TRACE</span><strong>{labels[level]}</strong><small>{level==='home'?'ROOT + SATELLITES':`DEPTH ${depth} · NAYAN PERSISTENT`}</small></aside>
  <aside className="flow-controls"><button onClick={()=>zoom(.9)} aria-label="Zoom out"><Minus size={14}/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>zoom(1.1)} aria-label="Zoom in"><Plus size={14}/></button><button onClick={()=>{setScale(level==='home'?1:.92);setCamera({x:0,y:0})}} aria-label="Reset"><RotateCcw size={14}/></button><button onClick={()=>{setScale(level==='home'?1:.92);setCamera({x:0,y:0})}} aria-label="Center"><LocateFixed size={14}/></button></aside>
  <footer className="flow-footer"><div><small>PHASE 04</small><strong>CONTINUOUS GRAPH NAVIGATION</strong></div><div className="flow-status">{level==='home'?'HOME / ROOT + SATELLITES':`${labels[level]} / ANCESTRY PRESERVED`}</div><div className="flow-footer-right">SCROLL / TRAVEL · DRAG / PAN · CLICK / OPEN</div></footer>
 </main>
}
