'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ExternalLink, LocateFixed, Minus, Plus, RotateCcw } from 'lucide-react';

type Level='home'|'projects'|'jobpilot'|'ironakhada'|'portfolio'|'photography'|'pylauncher'|'experience'|'skills'|'philosophy'|'contact'|'about';
type P={x:number;y:number};
type N={id:string;label:string;description?:string;href?:string;child?:Level;kind?:'primary'|'project'|'detail'|'satellite'};
type D={eyebrow:string;title:string;body:string;tags:string[];links?:{label:string;href:string}[]};

const labels:Record<Level,string>={home:'ORIGIN',projects:'PROJECTS',jobpilot:'JOBPILOT AI',ironakhada:'IRON AKHADA',portfolio:'FLOW PORTFOLIO',photography:'GHOUL PHOTOGRAPHY',pylauncher:'PYLAUNCHER',experience:'EXPERIENCE',skills:'CAPABILITIES',philosophy:'THINKING',contact:'CONTACT',about:'ABOUT'};
const parent:Partial<Record<Level,Level>>={projects:'home',jobpilot:'projects',ironakhada:'projects',portfolio:'projects',photography:'projects',pylauncher:'projects',experience:'home',skills:'home',philosophy:'home',contact:'home',about:'home'};
const mk=(id:string,label:string,description?:string,child?:Level,kind:N['kind']='detail',href?:string):N=>({id,label,description,child,kind,href});

const children:Record<Level,N[]>= {
 home:[mk('projects','PROJECTS',undefined,'projects','primary'),mk('experience','EXPERIENCE',undefined,'experience','primary'),mk('skills','CAPABILITIES',undefined,'skills','primary'),mk('philosophy','THINKING',undefined,'philosophy','primary'),mk('contact','CONTACT',undefined,'contact','primary'),mk('about','ABOUT',undefined,'about','primary'),mk('jobpilot','JOBPILOT AI','AI-assisted job outreach','jobpilot','satellite'),mk('ironakhada','IRON AKHADA','Fitness radio experience','ironakhada','satellite'),mk('portfolio','FLOW PORTFOLIO','This interface as a system','portfolio','satellite'),mk('photography','GHOUL PHOTO','Cinematic photography archive','photography','satellite'),mk('pylauncher','PYLAUNCHER','Python desktop utility','pylauncher','satellite'),mk('engineering','ANALYSER','Engineer · Nov 2025 – Jun 2026'),mk('manufacturing','ASHOK LEYLAND','Graduate Apprentice · Aug 2024 – Jul 2025')],
 projects:[mk('jobpilot','JOBPILOT AI','AI-assisted job outreach workflow','jobpilot','project'),mk('ironakhada','IRON AKHADA','Fitness radio and live presence','ironakhada','project'),mk('portfolio','FLOW PORTFOLIO','Portfolio navigation as a connected system','portfolio','project'),mk('photography','GHOUL PHOTOGRAPHY','Cinematic photography archive','photography','project'),mk('pylauncher','PYLAUNCHER','Python utility and desktop workflow','pylauncher','project')],
 jobpilot:[mk('jp-problem','PROBLEM','Reduce repetitive job-search and outreach work.'),mk('jp-system','SYSTEM','Import, matching, drafting, approval and outreach.'),mk('jp-tech','TECHNOLOGY','A modern web stack with AI-assisted workflows.'),mk('jp-next','NEXT.JS','Application framework and product shell.'),mk('jp-typescript','TYPESCRIPT','Typed application foundation.'),mk('jp-ai','AI AGENT','Automation layer for repeatable outreach work.'),mk('jp-api','APIS','Connect workflow stages and external services.')],
 ironakhada:[mk('ia-fitness','FITNESS','Fitness-focused product direction.'),mk('ia-journey','USER JOURNEY','Entering, discovering and training.'),mk('ia-build','BUILD','Responsive product implementation.'),mk('ia-audio','STREAMED AUDIO','Core listening function.'),mk('ia-presence','LIVE PRESENCE','Listener presence inside the experience.'),mk('ia-stations','TRAINING STATIONS','Training-focused navigation.')],
 portfolio:[mk('pf-flow','FLOW','Navigation as a connected system.'),mk('pf-interactive','INTERACTION','Drag, zoom, hover, click and keyboard.'),mk('pf-architecture','ARCHITECTURE','One graph model drives layout, camera and rendering.'),mk('pf-responsive','RESPONSIVE','The topology adapts rather than simply shrinking.'),mk('pf-trace','TRACE','Ancestors remain visible as a persistent exploration path.'),mk('pf-access','ACCESSIBILITY','Semantic controls, focus states and reduced motion.')],
 photography:[mk('gp-archive','ARCHIVE','Cinematic photography archive.'),mk('gp-gallery','GALLERY','Responsive visual browsing.'),mk('gp-automation','AUTOMATION','Gemini AI and Instagram API workflows.'),mk('gp-responsive','RESPONSIVE','Visual experience across screen sizes.'),mk('gp-content','CONTENT','Repeatable content workflow.')],
 pylauncher:[mk('pl-python','PYTHON','Python application development.'),mk('pl-launcher','LAUNCHER','Utility-oriented launcher experience.'),mk('pl-interface','INTERFACE','Desktop interaction and usability.'),mk('pl-utility','UTILITY','Practical workflow over unnecessary complexity.')],
 experience:[mk('ex-engineering','ENGINEER','Analyser Instrument Company · Nov 2025 – Jun 2026'),mk('ex-manufacturing','ASHOK LEYLAND','Graduate Apprentice Trainee · Aug 2024 – Jul 2025'),mk('ex-proposals','TECHNICAL PROPOSALS','Compliance documentation and tender proposals.'),mk('ex-support','CUSTOMER SUPPORT','Product specifications and technical queries.'),mk('ex-operations','SHIFT OPERATIONS','100+ person team, SAP NetWeaver and Siemens HMI.'),mk('ex-quality','QUALITY','Root-cause analysis and enhanced inspection measures.')],
 skills:[mk('sk-javascript','JAVASCRIPT','Core web language.'),mk('sk-react','REACT','Interactive UI development.'),mk('sk-htmlcss','HTML / CSS','Web structure, styling and responsive systems.'),mk('sk-python','PYTHON','Application development.'),mk('sk-fastapi','FASTAPI','Python API development.'),mk('sk-node','NODE.JS','JavaScript runtime and tooling.'),mk('sk-rest','REST APIS','API-driven integrations.'),mk('sk-git','GIT / GITHUB','Source control and delivery.'),mk('sk-actions','GITHUB ACTIONS','Repository automation and CI.'),mk('sk-responsive','RESPONSIVE WEB','Mobile and desktop interfaces.')],
 philosophy:[mk('ph-root','FIND THE ROOT','Understand the underlying problem first.'),mk('ph-system','BUILD THE SYSTEM','Think frontend, backend, deployment and workflow together.'),mk('ph-leverage','SHIP WITH LEVERAGE','Use AI-assisted development to move faster without outsourcing judgment.'),mk('ph-working','WORKING SOFTWARE','Prefer useful, functioning software.'),mk('ph-document','DOCUMENT','Make decisions and processes understandable.'),mk('ph-improve','KEEP IMPROVING','Use feedback, testing and iteration.')],
 contact:[mk('ct-email','EMAIL','nayanasati2001@gmail.com',undefined,'detail','mailto:nayanasati2001@gmail.com'),mk('ct-linkedin','LINKEDIN','Professional profile.',undefined,'detail','https://linkedin.com/in/nayan-1209-asati'),mk('ct-github','GITHUB','Code and repositories.',undefined,'detail','https://github.com/Nayan1209'),mk('ct-phone','PHONE','+91 6262055238',undefined,'detail','tel:+916262055238'),mk('ct-location','LOCATION','Sagar, Madhya Pradesh, India.'),mk('ct-open','OPEN TO','Professional conversations and opportunities.')],
 about:[mk('ab-engineer','ENGINEER','Electrical engineering foundation.'),mk('ab-developer','DEVELOPER','Self-taught full-product developer.'),mk('ab-education','EDUCATION','B.Tech Electrical Engineering.'),mk('ab-certifications','CERTIFICATIONS','CSS/Bootstrap/JavaScript/PHP, AI Tools Workshop and apprenticeship.'),mk('ab-languages','LANGUAGES','Hindi native and English professional.'),mk('ab-location','BASED IN','Sagar, Madhya Pradesh, India.'),mk('ab-approach','APPROACH','Engineering discipline plus practical software delivery.')]
};

const details:Record<Level,D>={
 home:{eyebrow:'NAYAN ASATI / ORIGIN',title:'Creative engineer. Technical builder.',body:'I build complete digital products end-to-end, combining engineering discipline, systems thinking and a strong instinct for interaction.',tags:['Engineering','Product development','Systems thinking']},
 projects:{eyebrow:'NAYAN ASATI / SELECTED WORK',title:'Products, not page mockups.',body:'A small set of practical systems where product thinking, engineering and interface design meet.',tags:['JobPilot AI','Iron Akhada','Flow Portfolio','Ghoul Photography','PyLauncher']},
 jobpilot:{eyebrow:'PROJECT / JOBPILOT AI',title:'Job outreach as a system.',body:'An AI-assisted workflow organized around repeatable stages instead of disconnected manual work.',tags:['Next.js','TypeScript','AI','APIs'],links:[{label:'OPEN GITHUB',href:'https://github.com/Nayan1209/jobpilot-ai'}]},
 ironakhada:{eyebrow:'PROJECT / IRON AKHADA',title:'A fitness radio experience.',body:'A web-based fitness radio experience with streamed audio, live listener presence, training stations and immersive interaction.',tags:['Next.js','React','TypeScript','Cloudflare']},
 portfolio:{eyebrow:'PROJECT / FLOW PORTFOLIO',title:'A portfolio that behaves like a network.',body:'Navigation is the interface: nodes expand, ancestors persist, and the path itself becomes part of the story.',tags:['Next.js','React','TypeScript','Interaction']},
 photography:{eyebrow:'PROJECT / GHOUL PHOTOGRAPHY',title:'A cinematic visual archive.',body:'A responsive photography experience focused on visual discovery with automated content workflows.',tags:['HTML5','CSS3','JavaScript','Gemini AI'],links:[{label:'OPEN PROJECT',href:'https://ghoul-photography.vercel.app/'}]},
 pylauncher:{eyebrow:'PROJECT / PYLAUNCHER',title:'A focused Python utility.',body:'A practical launcher and desktop workflow built around utility, speed and direct interaction.',tags:['Python','Desktop','Utility']},
 experience:{eyebrow:'NAYAN ASATI / EXPERIENCE',title:'Engineering in practice.',body:'Technical proposals, customer support, shift operations, SAP/HMI workflows, root-cause analysis and quality improvement.',tags:['Analyser Instrument Company','Ashok Leyland','Quality']},
 skills:{eyebrow:'NAYAN ASATI / CAPABILITIES',title:'A practical technical stack.',body:'Web development, Python, APIs, source control, automation and responsive product engineering.',tags:['JavaScript','React','Python','FastAPI','GitHub']},
 philosophy:{eyebrow:'NAYAN ASATI / THINKING',title:'Think. Build. Ship.',body:'Find the root, build the system, ship working software, document decisions and keep improving.',tags:['Root cause','Systems thinking','Working software']},
 contact:{eyebrow:'NAYAN ASATI / CONTACT',title:'Open a connection.',body:'Choose a channel. The network stays intact while the relevant action opens.',tags:['Email','LinkedIn','GitHub','Phone']},
 about:{eyebrow:'NAYAN ASATI / ABOUT',title:'Engineer at the core.',body:'Electrical engineering education, manufacturing experience and self-taught software development come together in a practical approach to solving problems.',tags:['B.Tech Electrical Engineering','Developer','Manufacturing']}
};

const pathTo=(level:Level)=>{const r:Level[]=[];let c:Level|undefined=level;while(c){r.unshift(c);c=parent[c]}return r};
const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;

export default function Home(){
 const [level,setLevel]=useState<Level>('home'),[scale,setScale]=useState(1),[camera,setCamera]=useState<P>({x:0,y:0}),[viewport,setViewport]=useState({width:1440,height:900}),[hovered,setHovered]=useState<string|null>(null),[selected,setSelected]=useState('nayan'),[moving,setMoving]=useState(false),[reduced,setReduced]=useState(false);
 const stage=useRef<HTMLElement>(null),cameraRef=useRef(camera),scaleRef=useRef(scale),raf=useRef<number|null>(null),moveRaf=useRef<number|null>(null);
 const drag=useRef({active:false,id:-1,sx:0,sy:0,cx:0,cy:0,lx:0,ly:0,lt:0}),velocity=useRef<P>({x:0,y:0});
 const path=useMemo(()=>pathTo(level),[level]),active=children[level],mobile=viewport.width<720,compact=viewport.width<980;
 useEffect(()=>{cameraRef.current=camera},[camera]);useEffect(()=>{scaleRef.current=scale},[scale]);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),f=()=>setReduced(m.matches);f();m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);
 useEffect(()=>{const e=stage.current;if(!e)return;const o=new ResizeObserver(([x])=>setViewport({width:x.contentRect.width,height:x.contentRect.height}));o.observe(e);return()=>o.disconnect()},[]);
 useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current);if(moveRaf.current)cancelAnimationFrame(moveRaf.current)},[]);
 const positions=useMemo(()=>{const m=new Map<string,P>(),w=viewport.width,h=viewport.height;if(level==='home'){m.set('nayan',{x:0,y:mobile?-4:0});const prim=['projects','experience','skills','philosophy','contact','about'],rx=mobile?Math.min(w*.34,150):Math.min(w*.28,360),ry=mobile?Math.min(h*.31,220):Math.min(h*.29,280);prim.forEach((id,i)=>{const a=-Math.PI/2+i*Math.PI/3;m.set(id,{x:Math.cos(a)*rx,y:Math.sin(a)*ry})});if(mobile){[['jobpilot',-.34,-.30],['ironakhada',.34,-.30],['portfolio',-.36,.29],['photography',.36,.29],['pylauncher',0,.40],['engineering',-.34,.02],['manufacturing',.34,.02]].forEach(([id,x,y])=>m.set(id as string,{x:(x as number)*w,y:(y as number)*h}))}else{[['jobpilot',-360,-210],['ironakhada',-410,-15],['portfolio',-350,200],['photography',350,-15],['pylauncher',390,190],['engineering',-135,-330],['manufacturing',135,-330]].forEach(([id,x,y])=>m.set(id as string,{x:x as number,y:y as number}))}return m}const focusX=mobile?20:compact?70:105,step=mobile?112:compact?150:184;m.set('nayan',{x:focusX-Math.min(path.length,4)*step,y:0});path.slice(1).forEach((id,i)=>m.set(id,{x:focusX-(path.length-1-i)*step,y:0}));m.set(level,{x:focusX,y:0});const rx=mobile?Math.min(w*.29,145):compact?175:215,ry=mobile?Math.min(h*.23,145):compact?190:220,start=mobile?-Math.PI*.86:-Math.PI*.88,span=mobile?Math.PI*1.72:Math.PI*1.76;active.forEach((n,i)=>{const t=active.length===1?.5:i/(active.length-1),a=start+t*span;m.set(n.id,{x:focusX+Math.cos(a)*rx,y:Math.sin(a)*ry})});return m},[active,compact,level,mobile,path,viewport]);
 const visible=useMemo(()=>{const m=new Map<string,N>();m.set('nayan',mk('nayan','NAYAN ASATI',undefined,undefined,'primary'));path.slice(1).forEach(id=>m.set(id,mk(id,labels[id],undefined,undefined,'primary')));active.forEach(n=>m.set(n.id,n));return [...m.values()]},[active,path]);
 const reset=useCallback(()=>{setScale(level==='home'?1:mobile?.76:.86);setCamera({x:0,y:0})},[level,mobile]);
 const navigate=useCallback((n:N)=>{if(n.id==='nayan'){setLevel('home');setSelected('nayan');setScale(1);setCamera({x:0,y:0});return}if(n.child){const d=pathTo(n.child).length-1;setLevel(n.child);setSelected(n.id);setScale(reduced?clamp(.94-d*.04,.76,.94):clamp(.9-d*.035,.76,.9));setCamera({x:0,y:0});return}if(n.href)window.open(n.href,'_blank','noopener,noreferrer');setSelected(n.id)},[reduced]);
 const zoom=useCallback((factor:number,origin?:P)=>setScale(cur=>{const next=clamp(cur*factor,mobile?.62:.55,1.7);if(origin){const r=next/cur;setCamera(c=>({x:origin.x-(origin.x-c.x)*r,y:origin.y-(origin.y-c.y)*r}))}return next},[mobile]);
 const animate=useCallback((target:P,targetScale:number)=>{if(reduced){setCamera(target);setScale(targetScale);return}const sC=cameraRef.current,sS=scaleRef.current,start=performance.now();if(raf.current)cancelAnimationFrame(raf.current);const f=(now:number)=>{const p=clamp((now-start)/600,0,1),e=1-Math.pow(1-p,4);setCamera({x:lerp(sC.x,target.x,e),y:lerp(sC.y,target.y,e)});setScale(lerp(sS,targetScale,e));if(p<1)raf.current=requestAnimationFrame(f)};raf.current=requestAnimationFrame(f)},[reduced]);
 const nodeSize=(n:N)=>n.id==='nayan'?(mobile?118:164):n.id===level?(mobile?104:148):n.kind==='primary'?(mobile?72:94):n.kind==='project'?(mobile?88:104):n.kind==='detail'?(mobile?70:82):(mobile?54:62);
 const hit=useCallback((x:number,y:number)=>{const r=stage.current?.getBoundingClientRect();if(!r)return null;const q={x:x-(r.left+r.width/2),y:y-(r.top+r.height/2)};for(const n of [...visible].reverse()){const p=positions.get(n.id);if(!p)continue;const s=nodeSize(n),nx=p.x*scaleRef.current+cameraRef.current.x,ny=p.y*scaleRef.current+cameraRef.current.y;if(Math.hypot(q.x-nx,q.y-ny)<=s*scaleRef.current/2+18)return n}return null},[level,mobile,positions,visible]);
 const focus=useCallback((n:N)=>{const p=positions.get(n.id);if(!p)return;if(n.child){navigate(n);return}setSelected(n.id);const s=clamp(scaleRef.current*(mobile?1.08:1.12),.72,1.25);animate({x:-p.x*s,y:-p.y*s},s)},[animate,mobile,navigate,positions]);
 const wheel=(e:React.WheelEvent<HTMLElement>)=>{e.preventDefault();const r=stage.current?.getBoundingClientRect();if(!r)return;const origin={x:e.clientX-(r.left+r.width/2),y:e.clientY-(r.top+r.height/2)},n=hit(e.clientX,e.clientY);if(n&&e.deltaY<-18){focus(n);return}zoom(e.deltaY<0?1.045:.955,origin)};
 const down=(e:React.PointerEvent<HTMLElement>)=>{if((e.target as Element).closest('[data-node],button,a'))return;drag.current={active:true,id:e.pointerId,sx:e.clientX,sy:e.clientY,cx:cameraRef.current.x,cy:cameraRef.current.y,lx:e.clientX,ly:e.clientY,lt:performance.now()};velocity.current={x:0,y:0};setMoving(true);e.currentTarget.setPointerCapture(e.pointerId)};
 const move=(e:React.PointerEvent<HTMLElement>)=>{const d=drag.current;if(!d.active||d.id!==e.pointerId)return;const now=performance.now(),dt=Math.max(8,now-d.lt);velocity.current={x:(e.clientX-d.lx)/dt*16,y:(e.clientY-d.ly)/dt*16};d.lx=e.clientX;d.ly=e.clientY;d.lt=now;const next={x:d.cx+e.clientX-d.sx,y:d.cy+e.clientY-d.sy};if(moveRaf.current)cancelAnimationFrame(moveRaf.current);moveRaf.current=requestAnimationFrame(()=>setCamera(next))};
 const up=(e:React.PointerEvent<HTMLElement>)=>{const d=drag.current;if(!d.active||d.id!==e.pointerId)return;d.active=false;setMoving(false);if(reduced)return;if(raf.current)cancelAnimationFrame(raf.current);const coast=()=>{velocity.current.x*=.9;velocity.current.y*=.9;if(Math.abs(velocity.current.x)+Math.abs(velocity.current.y)<.2)return;setCamera(c=>({x:c.x+velocity.current.x,y:c.y+velocity.current.y}));raf.current=requestAnimationFrame(coast)};raf.current=requestAnimationFrame(coast)};
 const key=(e:React.KeyboardEvent<HTMLElement>)=>{if(e.key==='Escape'){setLevel('home');setSelected('nayan');setScale(1);setCamera({x:0,y:0})}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(1.08)}else if(e.key==='-'){e.preventDefault();zoom(.92)}else if(e.key==='Home'){e.preventDefault();reset()}else if(e.key==='Backspace'&&level!=='home'){e.preventDefault();const p=parent[level]??'home';setLevel(p);setSelected(p==='home'?'nayan':p);setScale(p==='home'?1:mobile?.76:.86);setCamera({x:0,y:0})}};
 const activeNode=visible.find(n=>n.id===(hovered??selected)),detail=details[level];
 const edges=useMemo(()=>{const e:Array<{key:string;a:string;b:string;active?:boolean;secondary?:boolean}>=[];path.slice(1).forEach((id,i)=>e.push({key:`p-${id}`,a:path[i],b:id,active:selected===id||hovered===id}));active.forEach(n=>e.push({key:`c-${n.id}`,a:level,b:n.id,active:selected===n.id||hovered===n.id}));if(level==='home')[['projects','jobpilot'],['projects','ironakhada'],['projects','portfolio'],['projects','photography'],['projects','pylauncher'],['experience','engineering'],['experience','manufacturing']].forEach(([a,b])=>e.push({key:`s-${b}`,a,b,secondary:true}));return e},[active,hovered,level,path,selected]);
 return <main className={`flow ${moving?'is-moving':''} ${reduced?'motion-reduced':''}`} ref={stage} tabIndex={0} onWheel={wheel} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onKeyDown={key} aria-label="Nayan Asati interactive portfolio network">
  <div className="flow-atmosphere" aria-hidden="true"><div className="atmosphere-orbit orbit-one"/><div className="atmosphere-orbit orbit-two"/><div className="atmosphere-noise"/><div className="atmosphere-vignette"/></div>
  <header className="flow-header"><button className="flow-wordmark" onClick={()=>navigate(mk('nayan','NAYAN ASATI'))} aria-label="Return to origin">FLOW<i>.</i></button><div className="flow-header-center"><span className="header-kicker">INTERACTIVE SYSTEM / 01</span><span className="header-line"/><span>{labels[level]}</span></div><div className="flow-header-meta"><span>ENGINEER × DEVELOPER</span><span>MP / INDIA</span></div></header>
  <div className="flow-trace" aria-label="Current navigation path">{path.map((id,i)=><span key={`${id}-${i}`} className={i===path.length-1?'current':''}>{labels[id]}{i<path.length-1&&<b>→</b>}</span>)}</div>
  <section className="flow-stage" aria-label="Interactive network. Drag to pan, scroll to zoom, click nodes to explore."><div className="flow-world" style={{transform:`translate3d(${camera.x}px,${camera.y}px,0) scale(${scale})`}}><svg className="flow-lines" viewBox="-800 -500 1600 1000" aria-hidden="true">{edges.map(e=>{const a=positions.get(e.a),b=positions.get(e.b);return a&&b?<line key={e.key} className={`${e.active?'active ':''}${e.secondary?'secondary':''}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}</svg><div className="flow-origin-mark" aria-hidden="true"/>{visible.map(n=>{const p=positions.get(n.id);if(!p)return null;const root=n.id==='nayan',focusNode=n.id===level,ancestor=path.includes(n.id as Level),activeNodeClass=hovered===n.id||selected===n.id||focusNode;return <button key={n.id} data-node={n.id} className={`flow-node ${root?'root-node ':''}${focusNode?'focus-node ':''}${ancestor?'ancestor-node ':''}${n.kind??''}${activeNodeClass?' is-active':''}`} style={{left:`calc(50% + ${p.x}px)`,top:`calc(50% + ${p.y}px)`,width:nodeSize(n),height:nodeSize(n)}} onClick={()=>navigate(n)} onDoubleClick={()=>focus(n)} onMouseEnter={()=>setHovered(n.id)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(n.id)} onBlur={()=>setHovered(null)} aria-label={`${n.label}${n.description?` — ${n.description}`:''}`}><span className="node-ring" aria-hidden="true"/><span className="node-pulse" aria-hidden="true"/><span className="node-core"><span>{n.label}</span>{root&&<small>ORIGIN</small>}</span>{n.description&&<span className="node-description">{n.description}</span>}</button>})}</div></section>
  <div className="flow-guide" aria-hidden="true"><span>SCROLL</span><i>TRAVEL</i><span>DRAG</span><i>PAN</i><span>CLICK</span><i>ENTER</i></div>
  {level!=='home'&&<button className="flow-back" onClick={()=>{const p=parent[level]??'home';setLevel(p);setSelected(p==='home'?'nayan':p);setScale(p==='home'?1:mobile?.76:.86);setCamera({x:0,y:0})}}><ArrowLeft size={14}/><span>BACK</span></button>}
  <aside className="flow-detail" aria-live="polite"><div className="detail-index"><span>{detail.eyebrow}</span><span>{String(path.length).padStart(2,'0')}</span></div><h1>{activeNode?.id&&activeNode.id!=='nayan'?activeNode.label:detail.title}</h1><p>{activeNode?.description??detail.body}</p><div className="detail-tags">{detail.tags.map(t=><span key={t}>{t}</span>)}</div>{detail.links&&<div className="detail-links">{detail.links.map(l=><a key={l.href} href={l.href} target="_blank" rel="noreferrer">{l.label}<ExternalLink size={12}/></a>)}</div>}</aside>
  <aside className="flow-path-info" aria-hidden="true"><span>ACTIVE TRACE</span><strong>{labels[level]}</strong><small>{level==='home'?'ORIGIN + SYSTEM SATELLITES':`DEPTH ${path.length-1} / ANCESTRY PRESERVED`}</small></aside>
  <aside className="flow-controls" aria-label="Graph controls"><button onClick={()=>zoom(.9)} aria-label="Zoom out"><Minus size={14}/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>zoom(1.1)} aria-label="Zoom in"><Plus size={14}/></button><button onClick={reset} aria-label="Reset view"><RotateCcw size={14}/></button><button onClick={()=>animate({x:0,y:0},level==='home'?1:mobile?.76:.86)} aria-label="Center view"><LocateFixed size={14}/></button></aside>
  <footer className="flow-footer"><div><span>FLOW / NAYAN ASATI</span><strong>CREATIVE ENGINEER · TECHNICAL ARCHITECT</strong></div><div className="footer-status"><i/><span>{level==='home'?'SYSTEM READY':'TRACE ACTIVE'}</span></div><div className="footer-right"><span>© 2026</span><span>REDUCED MOTION {reduced?'ON':'AVAILABLE'}</span></div></footer>
 </main>
}